
#   # Qemu parameters
#
#  expects array of strings (`["X", "Y"]`)
#
#   ## Default parameters
#   - stored in the `default` table
#   - used when parameters for target are not found
#
#   ## Target specific parameters
#   - stored in `<arch>` table (`x86_64`, `arm64`, ...)

#   # Built-in variables
#   - in-place substituted with its values
#
#   1. `{ISO}` = path to the ISO file for this target
#   2. `{ARCH}` = current architecture


[default]
normal=["-drive", "file={ISO},if=virtio,media={media},discard=unmap"]
debug=["-drive", "file={ISO},if=virtio,media={media},discard=unmap"]
    #   parameters in debug mode

[x86_64]
normal=["-drive", "file={ISO},if=virtio,media={media},discard=unmap"]
debug=["-drive", "file={ISO},if=virtio,media={media},discard=unmap"]

[arm64]
normal=["-drive", "file={ISO},if=virtio,media={media},discard=unmap"]
debug=["-drive", "file={ISO},if=virtio,media={media},discard=unmap"]


[vars]
#   You can define your own variables here
#       note that custom variables can only include built-in variables
media="disk"