#   you can specify your qemu parameters here
#   this file will be injected into the script itself so you can use whatever parameters that can be found in util-<arch>.conf

#   variables that you can use:
#       current_arch = the script iterates through targets, this is the current one
#       iso = each target build has its iso, this is it
#   also look into files/base/scripts.conf

#   you need to specify the qemu_parameters and qemu_parameters_debug variables


qemu_parameters="-drive file=$iso,if=virtio,media=disk,discard=unmap"
    #   parameters for regular emulation

qemu_parameters_debug="-drive file=$iso,if=virtio,media=disk,discard=unmap"
    #   parameters for emulation in debug mode