#   This file is here to make rust-analyzer shut up :)
#       (is not used by rust-script)

[package]
name = "util"
description="convenience program for project management"
version = "0.1.0"
edition = "2024"
license="MIT"

[profile.dev]
panic="abort"



[profile.release]
opt-level = 3

[dependencies]
colored = "3.0.0"
serde = { version="1.0.228", features = ["derive"] }
toml = "0.9.7"



[[bin]]
name="example"
path="src/main.rs"

[[bin]]
name="conf"
path="src/conf.rs"
