[util]
configured=true
built=true
xorriso="/usr/bin/xorriso"
iso_name="BaseOS"
arch=["x86_64", "arm64"]


[kernel]
name="BaseOS"
version="0.5.0"
release="BaseOS-v0.5.0"


[os]
name="BaseOS"
version="0.0.1"
release="BaseOS-v0.0.1"


[x86_64]
compiler="/home/sam/.cargo/bin/cargo"
emulator="/usr/bin/qemu-system-x86_64"

