#!/bin/bash


source "$PWD/files/base/scripts.conf"

if [ "$#" -lt 3 ]; then
    error "$(blue change): expected at least 3 parameters"
    exit 1
fi

file="$(echo $1 | tr '[:upper:]' '[:lower:]')"
attr="$(echo $2 | tr '[:upper:]' '[:lower:]')"
value="$3"

if [[ "$attr" != name && "$attr" != version && "$attr" != release ]]; then
    error "unknown attribue '$attr'"
    note "expected $(blue "'name', 'version' or 'release'")"
    exit 1
fi


case $file in
    os)
        sed -i '' "s/^$attr=.*/$attr=$value/" $OS_CONFIG
    ;;
    kernel)
        sed -i '' "s/^$attr=.*/$attr=$value/" $KERNEL_CONFIG
    ;;
    *)
        error "unknown section '$file'"
        note "expected $(blue "'os' or 'kernel'")"
        exit 1
    ;;
esac