#!/bin/bash


black() { echo -e "\033[0;30m$1\033[0m"; }
red() { echo -e "\033[0;31m$1\033[0m"; }
green() { echo -e "\033[0;32m$1\033[0m"; }
yellow() { echo -e "\033[1;33m$1\033[0m"; }
blue() { echo -e "\033[0;34m$1\033[0m"; }
magenta() { echo -e "\033[0;35m$1\033[0m"; }
cyan() { echo -e "\033[0;36m$1\033[0m"; }
white() { echo -e "\033[0m$1\033[0m"; }

error() { echo "$(red ERROR): $1"; }
warning() { echo "$(yellow WARNING): $1"; }
note() { echo "$(magenta NOTE): $1"; }

CONFIG_PATH=$PWD/config/
KERNEL_CONFIG=$CONFIG_PATH/kernel.conf
OS_CONFIG=$CONFIG_PATH/os.conf
UTIL_CONFIG=$CONFIG_PATH/util.conf
SCRIPTS=$PWD/files/base/scripts

source $UTIL_CONFIG

if [ "$#" -lt 3 ]; then
    error "$(blue change): expected at least 3 parameters"
    exit 1
fi

file="$(echo $1 | tr '[:upper:]' '[:lower:]')"
attr="$(echo $2 | tr '[:upper:]' '[:lower:]')"
value="$3"

if [[ "$attr" != name && "$attr" != version && "$attr" != release ]]; then
    error "unknown attribue '$attr'"
    note "expected $(blue "'name', 'version' or 'release'")"
    exit 1
fi


case $file in
    os)
        sed -i '' "s/^$attr=.*/$attr=$value/" $OS_CONFIG
    ;;
    kernel)
        sed -i '' "s/^$attr=.*/$attr=$value/" $KERNEL_CONFIG
    ;;
    *)
        error "unknown section '$file'"
        note "expected $(blue "'os' or 'kernel'")"
        exit 1
    ;;
esac