#!/bin/bash

source "$PWD/files/base/scripts.conf"

IFS=" "

archs=""
if [ "$#" != 0 ]; then
    for arg in "$@"; do
        a="$(echo $arg | tr '[:upper:]' '[:lower:]')"
        case $a in
            x86_64)
                archs="$archs x86_64"
            ;;
            arm64)
                archs="$archs aarch64"
            ;;
        esac
    done
else
    archs="$arch"
fi

cargo_params="--target-dir bin --verbose --target"


#   check for errors
cd ./kernel
IFS=" "
for a in $archs; do
    note "checking kernel for $a target"

    if [ -e "$(arch_config $a)" ]; then
        source $(arch_config $a)
    else
        error "configuration for $a target is missing"
        exit 2
    fi

    $compiler check $cargo_params "$(get_arch $a)-unknown-none"

    if [ "$?" == 0 ]; then
        echo
        echo "$(green "SUCCESS")"
    else
        error "check for $a failed"
        exit 2
    fi

done
cd ../

