#!/bin/bash


source "$PWD/files/base/scripts.conf"

if [ $# -eq 0 ]; then
    error "$(blue conf): expected at least 2 parameters: $(yellow architecture)"
    exit 1
fi

arch=()
iso_name=BaseOS     #   -<arch>.iso will be added by the build subcommand
    #   iso files are located in the ./files directory
all_tools_installed=true

#   resolve arch
for arg in "$@"; do
    i="$(echo $arg | tr '[:upper:]' '[:lower:]')"
    case $i in
        x86_64)
            if [[ ! " ${arch[@]} " =~ " ${i} " ]]; then
                arch+=("$i")
            fi
        ;;
        arm64)
            if [[ ! " ${arch[@]} " =~ " ${i} " ]]; then
                arch+=("$i")
            fi
        ;;
        aarch64)
            if [[ ! " ${arch[@]} " =~ " arm64 " ]]; then
                arch+=("arm64")
            fi
        ;;
        amd64)
            if [[ ! " ${arch[@]} " =~ " x86_64 " ]]; then
                arch+=("x86_64")
            fi
        ;;
        *)
            error "'$arg' is not valid architecture"
            exit 1
        ;;
    esac
done


#   create utility configuration
note "creating utility configuration"
echo "# This is util configuration, please do not change manually" > $UTIL_CONFIG
echo "configured=true" >> $UTIL_CONFIG
echo "xorriso=$(search_path xorriso)" >> $UTIL_CONFIG
echo "arch=\"${arch[@]}\"" >> $UTIL_CONFIG
echo "iso_name=$iso_name" >> $UTIL_CONFIG





#   build the limine commandline utility for this host
if [ -e "$LIMINE_CMDLINE" ]; then
    rm "$LIMINE_CMDLINE"
fi

gcc -o "$LIMINE_CMDLINE" "$LIMINE_PATH/limine.c"
if [ "$?" != 0 ]; then error "failed to build the limine command line utility"; exit 2; fi

if [ ! -e "$LIMINE_CMDLINE" ]; then
    error "failed to build the limine command line utility"
fi

note "limine cmdline utility build was successful"





#   find needed tools
c_compiler_midnames="-elf- -linux-gnu- -none-linux-gnu-"
IFS=" "
for i in "${arch[@]}"; do

    compiler=NONE
    compiler="$(search_path cargo)"
    qemu="$(search_path "qemu-system-$(get_arch $i)")"

    config_file="$(arch_config $i)"

    if [ "$compiler" == NONE ]; then
        warning "compiler for the $i target is missing"
        all_tools_installed=false
    fi

    if [ "$qemu" == NONE ]; then
        warning "emulator fot the $i target is missong"
        all_tools_installed=false
    fi

    note "creating configuration for the $i target"

    #   flush the arch config
    echo "# This is util $i target configuration, please do not edit manually" > $config_file
    echo "# Paths are relative to the system root" >> $config_file
    echo "compiler=$compiler" >> $config_file
    #echo "linker=$linker" >> $config_file
    echo "emulator=$qemu" >> $config_file

done


if [ ! -e $KERNEL_CONFIG ]; then
    echo "name=BaseOS-kernel" > $KERNEL_CONFIG
    echo "version=0.0.1" >> $KERNEL_CONFIG
    echo "release=BaseOS-v0.0.1" >> $KERNEL_CONFIG
fi

if [ ! -e $OS_CONFIG ]; then
    echo "name=BaseOS" > $OS_CONFIG
    echo "version=0.0.1" >> $OS_CONFIG
    echo "release=BaseOS-v0.0.1" >> $OS_CONFIG
fi

if [ "$?" == 0 ]; then
    note "note created cargo configuration file"
else
    error "failed to create cargo configuration file"
    exit 2
fi


if [ "$all_tools_installed" != true ]; then
    warning "some development dependencies are missing, try running $(green "./util dep install") and then $(green "./util reconf")"
fi
