#!/bin/bash

source "$PWD/files/base/scripts.conf"

#   needed packages
#       cargo
#       emulator (qemu)
#       xorriso

function check_package() {     #   returns if package should be added to the list regardles operation mode
    #   $1 = program name to search if fs
    #   $2 = program name
    if [ "$mode" == install ]; then
        if [ "$(search_path "$1")" == NONE ]; then
            echo OK
        else
            echo NONE
        fi
    else
        if [ "$(search_path "$1")" != NONE ]; then
            echo OK
        else
            echo NONE
        fi
    fi
}

function add_package() {        #   adds package if not installed/removed (returns OK if package was added to the list or NONE)
    #   $1 = program name to search in fs
    #   $2 = program name
    case "$(check_package "xorriso" xorriso)" in
        OK) packages="$packages xorriso"; echo OK ;;
        NONE) echo NONE ;;
    esac
}

#   check for no parameters
if [ "$#" -eq 0 ]; then
    error "please tell me what to do $(green "install or remove?")"
    exit 1
fi

#   check for no confirm
no_confirm="NO"
if [ "$#" -ge 2 ]; then
    if [ "$2" == "-y" ]; then
        no_confirm="YES"
    else
        error "unknown parameter $(red "$2")"
        exit 1
    fi
fi


pkg_list="rustup qemu xorriso"
packages=()


#   check if packages should be installed or removed
case "$(echo $1 | tr '[:upper:]' '[:lower:]')" in
    remove)
        mode=remove
        mode_str=removed
    ;;
    install)
        mode=install
        mode_str=installed
    ;;
    list)
        echo "all packages: $(blue "$pkg_list")"



        exit 0
    ;;
    *) error "unknown option $arg"; exit 1 ;;
esac


#   install rust
case $(check_package rustup rustup ) in
    OK)
        #   install rust
        note "installing rustup"
        warning "rustup installation will run script downloaded from the internet"

        if [ $(ask "do you wish to proceed") == y ]; then
            note "alright, the rustup installation will most likely need your attention"
            for i in {5..0}; do
                echo "starting in $i"
                sleep 1
            done
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

            if [ "$?" != 0 ]; then
                error "rustup installation failed"
                exit 2
            fi

        else
            note "skipping rustup installation"
        fi

        echo "$(red IMPORTANT): you may need to add rustup to your path (as listed above)"

        note "rustup installation successfull"

        old_ifs="$IFS"
        IFS=" "
        for i in $arch; do
            a="$(get_arch $i)"
            note "installing target for $a"

            rustup target add "$i-unknown-none"

            if [ "$?" != 0 ]; then
                error "failed to install target for $i"
                exit 2
            fi

        done
        IFS="$old_ifs"

    ;;
    NONE)
        note "$(blue rust) is already installed"
    ;;
esac


#   pacnage manager command
pm_command=NONE


case "$(uname)" in
    Darwin)
        #   MacOS
        if [ $(search_path brew) == NONE ]; then
            warning "Homebrew is not installed"

            if [ "$(ask "$(yellow "would you like mo to install it")")" == y ]; then
                /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
                if [ "$?" != 0 ]; then
                    error "Homebrew installation failed"
                    exit 2
                fi
            else
                error 'Sorry, unable to work without Homebrew on mac :('
                exit 2
            fi
        fi

        #   MAYBE FIXME: add packages?

        pm_command="brew $mode ${packages[@]}"
        
    ;;

    "Linux")
        #   Gather distro information
        source /etc/os-release


        case $(echo "$NAME" | awk '{print $1}') in
            "Fedora")

                #   check qemu
                IFS=" "
                for i in $arch; do
                    i="$(get_arch $i)"
                    #echo -n "$(add_package qemu-system-$i qemu)"
                    if [ "$(add_package qemu-system-$i qemu)" = "NONE" ]; then
                        note "$(blue qemu) is already $mode_str"
                        break
                    else
                        
                    fi
                done
                #packages="$(echo "$packages" | uniq)"
                awk -v RS=' ' '!seen[$0]++' <<< "$packages"

                echo packages: $packages


                if [ "$(add_package xorriso xorriso)" == "NONE" ];then
                    note "$(blue xorriso) is already $mode_str"
                fi

                exit

                #   find compiler
                # IFS=" "
                # for i in $arch; do
                #     i="$(get_arch $i)"

                #     case "$(check_package "qemu-system-$i" qemu)" in
                #         OK)
                #             packages="$packages qemu"
                #             break
                #         ;;
                #         NONE)
                #             note "$(blue qemu) is already $mode_str"
                #         ;;
                #     esac
                # done

                # #   check xorriso
                # case "$(check_package "xorriso" xorriso)" in
                #     OK)
                #         packages="$packages xorriso"
                #     ;;
                #     NONE)
                #         note "$(blue xorriso) is already installed"
                #     ;;
                # esac

                #   cc is needed for some parts of the kernel
                #case $(check_package "cc" "cc") in
                #    OK)
                #        packages="$packages rust-cc-devel"
                #    ;;
                #    NONE)
                #        note "$(blue cc) (rust-cc-devel) is already installed"
                #    ;;
                #esac

                pm_command="sudo dnf $mode ${packages[@]}"
                if [ "$no_confirm" == "YES" ]; then
                    pm_command="$pm_command -y"
                fi

            ;;
            *)
                error "Sorry, your Linux distro does not seem to be supported"
                exit 2
            ;;
        esac

    ;;


    *)
        error "Sorry, your operating system does not seem to be supported"
        exit 2
    ;;
esac



#   install or remove packages
if [ "${#packages[@]}" -eq 0 ]; then
    note "all packages are already $mode_str"
    exit
fi

if [ "$pm_command" == "NONE" ]; then
    error "critical internal error: package manager command not set (NONE)"
    exit 1
fi

if [ "$mode" == "install" ]; then
    note "installing these packages: $(blue "${packages[@]}")"
else
    note "removing these packages: $(blue "${packages[@]}")"
fi

if [[ "$no_confirm" == "YES" || $(ask "is this OK") == y ]]; then
    $pm_command

    if [ "$?" != 0 ]; then
        error "failed to install packages"
        exit 2
    fi

else
    note "no packages were installed"
    exit
fi