#!/bin/bash

#   TODO: revision

source "$PWD/files/base/scripts.conf"

if [ "$#" -eq 0 ]; then
    echo "$(green ./util) is simple script used to build and manage your OS project"
    echo "      $(note "util is meant to be run only in project root directory")"
    echo
    echo "subcommands:"
    echo "  $(blue conf) <arch> - configures the environment and finds needed tools"
    echo "  $(blue reconf)      - reconfigures the project (using different tools, ...)"
    echo "  $(blue build)       - builds the OS"
    echo "  $(blue run)         - runs the OS in emulator"
    echo "  $(blue dep)         - installs or removes the tools needed to build and run the operating system ($(red "needs internet connection"))"
    echo "  $(blue change)      - allows you to change project info"
    echo "  $(blue mkiso)       - creates bootable ISO for your OS"
    echo "  $(blue check)       - checks for errors"
    echo
    echo "$(magenta NOTE ): for more info use $(green "./util") help <subcommands>"
    echo "      for example: $(green "./util") $(blue "help build run") will show information about the $(blue build) and $(blue run) subcommand"

    echo

    echo "$(magenta NOTE): you can run multiple subcommands with $(green util)"
    echo "      for example: $(green ./util) $(blue "dep install + reconf") will install dependencies and reconfigure the project in one command"

else
    CMD="$(echo "$*" | tr '[:upper:]' '[:lower:]')"
fi

IFS=' '

if [ "$(echo $1 | tr '[:upper:]' '[:lower:]')" == "all" ]; then
    CMD="conf reconf build run dep change mkiso check"
fi


for i in $CMD; do
    case $i in 
        conf)
            echo "$(green ./util) $(blue conf)"
            echo "  $(yellow 'configures the environment and finds needed tools')"
            echo "  expects CPU architectures to be supported by the OS"
            echo
            echo "  supported CPU architectures: $(green x86_64), $(red arm64)"
            echo
            echo "  for example $(green ./util) $(blue "conf x86_64") will configure the project for the x86_64 architecture"
        ;;
        reconf)
            echo "$(green ./util) $(blue reconf)"
            echo "  $(yellow 'reconfigures the project if some tools have changed or are missing')"
        ;;
        build)
            echo "$(green ./util) $(blue build)"
            echo "  $(yellow 'builds your OS project') and constructs the ISO image structure"
            echo "  $(red 'if multiple architectures are selected, it also expects the <arch/s> parameter/s')"
            echo "          for instance: $(green ./util) $(blue 'build x86_64 arm64')"
            echo
            echo "  append $(blue debug) for debug options:"
            echo "          $(green ./util) $(blue "build debug") builds your operating system for debugging"
            echo "  append $(blue run) to automatically run it in emulator"
            echo "          $(green ./util) $(blue 'build run red debug') starts the emulator for debugging"
        ;;
        run)
            echo "$(green ./util) $(blue run)"
            echo "  $(yellow 'starts the last compiled operating system in the emulator')"
            echo
            echo "  append $(blue debug) to run with debug options"
            echo
            echo "  this subcommand reads from the $(green "./config/qemu-parameters.conf") file"
        ;;
        dep)
            echo "$(green ./util) $(blue dep)"
            echo "  $(yellow 'installs or removes the tools needed to build and run the operating system')"
            echo "  $(red 'internet connection is needed')"
            echo
            echo "  append $(blue install) to install all dependencies"
            echo "  append $(blue remove) to uninstall all dependencies"
            echo "      $(red "you may miss some of the uninstalled tools")"
            echo "  append $(blue -y) to not ask for confirmation"
            echo
            echo "  supported platforms:"
            echo "      $(green Fedora Linux), $(red Arch Linux), $(red Ubuntu), $(red Debian) $(red CentOS)"
            echo "      $(green MacOS) (brew), $(red FreeBSD), $(red OpenBSD)"
        ;;
        change)
            echo "$(green ./util) $(blue change)"
            echo "  $(yellow 'allows you to change project info')"
            echo
            echo "  available changes:"
            echo "      $(yellow os) $(blue name)/$(blue version)/$(blue release) changes OS name, version or release"
            echo "      $(yellow kernel) $(blue name)/$(blue version)/$(blue release) changes kernel name, version or release"
        ;;
        mkiso)
            echo "$(green ./util) $(blue mkiso)"
            echo "  $(yellow 'builds you a bootable ISO for target platforms') ($(red "the OS kernel must be built"))"
            echo 
            echo "  usage: $(green ./util) $(blue "mkiso <arch/s>")"
        ;;
        check)
            echo "$(green ./util) $(blue check)"
            echo "  $(yellow 'checks for errors')"
            echo
            echo "  usage: $(green ./util) $(blue 'check <arch/s>')"
        ;;
        *)
            if [ "$1" != $i ]; then
                error "unknown command '$i'"
                exit 1
            fi
        ;;
    esac
    echo;
done