#!/bin/bash

source "$PWD/files/base/scripts.conf"

iso="$PWD/iso"

function failure() {
    status="$?"
    error "$(blue mkiso): command failure: $BASH_COMMAND (exitted with status $status)"
    exit 1
}


set -eEuo pipefail
trap failure ERR

archs=""
debug=false
if [ "$#" != 0 ]; then
    for arg in "$@"; do
        a="$(echo $arg | tr '[:upper:]' '[:lower:]')"
        case $a in
            debug)
                debug=true
            ;;
            x86_64)
                archs="$archs x86_64"
            ;;
            arm64)
                archs="$archs aarch64"
            ;;
        esac
    done
else
    archs="$arch"
fi


IFS=" "
for a in $archs; do

    note "creating ISO for $a target"

    if [ -e "$iso-$(get_arch $a)" ]; then
        rm -rf $iso-$(get_arch $a)/*
    fi

    if [ ! -e "$(kernel_full $a)" ]; then
        error "kernel for $a target is missing"
        exit 2
    fi

    mkdir -p $iso/EFI/BOOT $iso/boot/limine
    cp $(kernel_full $a) $iso/boot/baseOS.bin

    if [ $debug == true ]; then
        limine_config="$LIMINE_PATH/configs/limine-debug.conf"
    else
        limine_config="$LIMINE_PATH/configs/limine.conf"
    fi


    cp $limine_config $LIMINE_PATH/limine-bios.sys $iso/boot/limine

    case $a in
        x86_64)
            efi_exe="BOOTX64.EFI"
        ;;
        *)
            error "target $iais not supported yet"
            efi_exe="BOOTX64.EFI"
        ;;
    esac

    echo "efi exe: $efi_exe"
    cp $LIMINE_PATH/$efi_exe $iso/EFI/BOOT/

    cp $LIMINE_PATH/limine-bios-cd.bin $LIMINE_PATH/limine-uefi-cd.bin $iso/


    xorriso -as mkisofs -R -r -J -b limine-bios-cd.bin\
	-no-emul-boot -boot-load-size 4 -boot-info-table -hfsplus -apm-block-size 2048\
	--efi-boot limine-uefi-cd.bin -efi-boot-part --efi-boot-image\
	--protective-msdos-label $iso -o "$(image_full $a)"

    $LIMINE_CMDLINE bios-install $(image_full $a)

done
