#!/bin/bash

source "$PWD/files/base/scripts.conf"

archs=""
debug=false
custom=false
arch_set=false
if [ "$#" != 0 ]; then
    for arg in "$@"; do
        a="$(echo $arg | tr '[:upper:]' '[:lower:]')"
        case $a in
            debug)
                debug=true
                ;;
            custom)
                custom=true
            ;;
            x86_64)
                archs="$archs x86_64"
                arch_set=true
            ;;
            arm64)
                archs="$archs aarch64"
                arch_set=true
            ;;
        esac
    done
fi

if [ "$arch_set" = false ]; then
    archs="$arch"
fi

cargo_params="--target-dir bin --verbose"
if [ "$debug" = false ]; then
    cargo_params="$cargo_params --release"
fi

IFS=" "
for a in $archs; do
    note "testing target $a"

    if [ ! -e ./tmp/kernel ]; then
        mkdir -p ./tmp/kernel
    fi

    if [ -e "$(arch_config $a)" ]; then
        source $(arch_config $a)
    else
        error "configuration for $a target is missing"
        exit 2
    fi


    #   compile rust code

    cd ./kernel
        if [ "$custom" = true ]; then
            $compiler build $cargo_params --target "$(get_arch $a)-unknown-none" --features "custom_testing"
        else
            $compiler build $cargo_params --target "$(get_arch $a)-unknown-none" --features "testing"
        fi

        if [ "$?" != 0 ]; then
            error "failed to compile kernel"
            exit 2
        fi

    cd ..

    #   copy compiled kernel into `files` directory
    cp $PWD/kernel/bin/$(get_arch $a)-unknown-none/release/baseOS $(kernel_full $a)

    rm -rf ./tmp/*

    $SCRIPTS/mkiso $a
    if [ "$?" != 0 ]; then
        error "failed to create image for $a"
        exit 1
    fi

    $SCRIPTS/run $a

done