timeout: 5

interface_branding: Welcome to BaseOS
interface_branding_color: 7
#   blue

editor_enabled: no

default_entry: 2

/BaseOS (KASLR on)
	protocol: limine
	kernel_path: boot():/boot/BaseOS.bin
    kaslr: yes

/BaseOS
	protocol: limine
	kernel_path: boot():/boot/BaseOS.bin
	kaslr: no



/BaseOS (troubleshoot)
	protocol: limine
	kernel_path: boot():/boot/BaseOS.bin
	kaslr: no
